sites:
  -
    addr: localhost
    port: 8089
    dir: E:\test server\static
    translates:
      -
        origin: .php # 欺骗性的后缀名
        current: .html
    redirects:
      -
        include: "[\\S]*\\.html"# 此功能用于单页
        exclude: ["index\\.html"]
        to: "index.html"
